export default {
    LOAD_ROOMS: 'HOME/LOAD_ROOMS',
    UPDATE_ROOMS: 'HOME/UPDATE_ROOMS',
    ROOMS_RESULT: 'HOME/ROOMS_RESULT',
    CREATE_ROOM: 'HOME/CREATE_ROOM',
    DELETE_ROOM: 'hOME/DELETE_ROOM',
    JOIN_ROOM: 'HOME/JOIN_ROOM',
    SET_MY_NAME: 'HOME/SET_MY_NAME',
}
